import 'package:flutter_riverpod/flutter_riverpod.dart';

/// This provider stores the current daily meal plan generated by NutriAI.
/// It is updated in the [HomeScreen] after a successful API call and
/// consumed by the [MealScreen] to display the diet plan.
final mealPlanStateProvider = StateProvider<Map<String, dynamic>?>((ref) {
  return null;
});
