class EmojiDecoder {
  /// A high-tech, robust decoder for malformed emoji strings.
  /// Intelligently parses and reconstructs escaped Unicode characters, 
  /// surrogate pairs, and broken JSON representations often generated by AI.
  static String decode(String? input) {
    try {
      if (input == null || input.trim().isEmpty) return '🍽️';
      String decoded = input.trim();
      
      // 1. Sanitize: Remove erroneous characters that AI sometimes inserts
      String cleaned = decoded.replaceAll('\n', '').replaceAll('\r', '').replaceAll(r'\', '');
      
      // 2. Look for high and low surrogate hex pairs
      final RegExp hexSurrogateRegExp = RegExp(r'(d8[0-9a-fA-F]{2})[^a-fA-F0-9]*(d[c-fC-F][0-9a-fA-F]{2})', caseSensitive: false);
      
      if (hexSurrogateRegExp.hasMatch(cleaned)) {
        String result = '';
        for (final match in hexSurrogateRegExp.allMatches(cleaned)) {
          try {
            int high = int.parse(match.group(1)!, radix: 16);
            int low = int.parse(match.group(2)!, radix: 16);
            result += String.fromCharCodes([high, low]);
          } catch (_) {}
        }
        // Validate it's UTF-16, not a replacement char, AND is actually in an emoji unicode block
        if (result.isNotEmpty && _isValidUtf16(result) && !result.contains('\uFFFD') && _isLikelyEmoji(result)) {
          return result;
        }
      }

      // 3. Extract single unicode characters (e.g., "u2600" -> ☀️)
      final RegExp hexSingleRegExp = RegExp(r'(?:u|\\u|\\n)([0-9a-fA-F]{4})', caseSensitive: false);
      if (hexSingleRegExp.hasMatch(decoded)) {
        String result = '';
        for (final match in hexSingleRegExp.allMatches(decoded)) {
          try {
            int code = int.parse(match.group(1)!, radix: 16);
            if (code < 0xD800 || code > 0xDFFF) {
              result += String.fromCharCode(code);
            }
          } catch (_) {}
        }
        if (result.isNotEmpty && _isValidUtf16(result) && !result.contains('\uFFFD') && _isLikelyEmoji(result)) {
          return result;
        }
      }

      // 4. If the string is already a valid Emoji character returned directly by AI
      if (_isValidUtf16(decoded) && !decoded.contains('\uFFFD')) {
         if (_isLikelyEmoji(decoded)) return decoded;
      }
      
      // 5. Default fallback for anything else
      return '🍽️';
    } catch (e) {
      // If ANY type of problem occurs, fallback to plate and spoon
      return '🍽️';
    }
  }

  /// Strictly checks if the string contains a codepoint in the standard emoji blocks.
  /// Prevents AI from hallucinating non-emoji unicode symbols (like U+1FB51) which render as question marks.
  static bool _isLikelyEmoji(String s) {
    if (s.isEmpty) return false;
    for (int r in s.runes) {
      if ((r >= 0x1F300 && r <= 0x1FAFF) || // Misc Symbols, Food, Transport, Pictographs Ext
          (r >= 0x2600 && r <= 0x27BF) ||   // Misc Symbols, Dingbats
          (r >= 0x2300 && r <= 0x23FF)) {   // Misc Technical
        return true;
      }
    }
    return false;
  }

  /// Verifies that the string contains well-formed UTF-16.
  /// This prevents the "Invalid argument(s): string is not well-formed UTF-16" 
  /// exception in Flutter's TextSpan.build.
  static bool _isValidUtf16(String s) {
    for (int i = 0; i < s.length; i++) {
      int code = s.codeUnitAt(i);
      if (code >= 0xD800 && code <= 0xDBFF) {
        // High surrogate MUST be followed by low surrogate
        if (i + 1 < s.length) {
          int next = s.codeUnitAt(i + 1);
          if (next >= 0xDC00 && next <= 0xDFFF) {
            i++; // skip next
            continue;
          }
        }
        return false; // Unpaired high
      }
      if (code >= 0xDC00 && code <= 0xDFFF) {
        return false; // Unpaired low
      }
    }
    return true;
  }
}
